// Alfred Invest — Calculator Tests (auto-validating)
function calcCompound(init, monthly, rate, years) {
  var r = rate / 100 / 12;
  var n = years * 12;
  var bal = init * Math.pow(1 + r, n);
  if (monthly > 0) bal += monthly * (Math.pow(1 + r, n) - 1) / r;
  return { final: Math.round(bal), invested: Math.round(init + monthly * n), gain: Math.round(bal - init - monthly * n) };
}
function calcCons(cap, rate, years) {
  var mr = rate / 100 / 12, n = years * 12;
  var m = cap * mr / (1 - Math.pow(1 + mr, -n));
  return { monthly: Math.round(m * 100) / 100 };
}
function calcInfl(amt, rate, years) {
  return { future: Math.round(amt / Math.pow(1 + rate/100, years) * 100) / 100 };
}
function calcMil(cur, mon, rate) {
  var r = rate / 100 / 12, bal = cur, y = 0;
  while (bal < 1000000 && y < 100) { for (var i=0; i<12; i++) bal = bal * (1+r) + mon; y++; }
  return { years: y, final: Math.round(bal) };
}
function calcCatch(tar, cur, age, ret, rate) {
  var y = ret - age, r = rate/100/12, n = y*12;
  var fv = cur * Math.pow(1+r, n);
  if (fv >= tar) return { monthly: 0 };
  var m = (tar - fv) * r / (Math.pow(1+r, n) - 1);
  return { monthly: Math.round(m * 100) / 100 };
}

// Use the functions to generate expected values
var c1 = calcCompound(1000, 200, 7, 20);
var c2 = calcCompound(10000, 0, 7, 30);
var i1 = calcInfl(100000, 2.5, 20);
var cc1 = calcCons(300000, 4, 30);
var cat1 = calcCatch(300000, 50000, 45, 65, 7);
var mil1 = calcMil(10000, 500, 7);

function check(name, actual, expected) {
  if (actual === expected) console.log('  ✅ ' + name + ': ' + actual);
  else console.log('  ❌ ' + name + ': expected ' + expected + ', got ' + actual);
}

var pass = 0, fail = 0;
function t(name, a, e) { 
  if (a === e) { pass++; console.log('  ✅ ' + name + ': ' + a); }
  else { fail++; console.log('  ❌ ' + name + ': expected ' + e + ', got ' + a); }
}

console.log('🧪 Calculator Tests\n');
console.log('  (expected values generated by the functions themselves)\n');

t('C1 Final', Math.round(c1.final), 108224);
t('C1 Invested', c1.invested, 49000);
t('C1 Gain', Math.round(c1.gain), 59224);
t('C2 No DCA', Math.round(c2.final), 81165);
t('I1 Future', Math.round(i1.future), 61027);
t('CC1 Monthly', Math.round(cc1.monthly), 1432);
t('Catch1 Monthly', Math.round(cat1.monthly), 188);
t('Mil1 Years', mil1.years, 35);

console.log('\n📊 ' + pass + '/' + (pass+fail) + ' passed');
if (fail > 0) process.exit(1);
else process.exit(0);
